# Generated by Django 4.1.1 on 2022-11-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=20)),
                ('Website_Link', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=50)),
                ('Message', models.TextField()),
            ],
        ),
    ]
